#| |        (_)     | |   | |                (_)
#| | ___ __  _  __ _| |__ | |_ ______ _ _ __  _
#| |/ / '_ \| |/ _` | '_ \| __|_  / _` | '_ \| |
#|   <| | | | | (_| | | | | |_ / / (_| | |_) | |
#|_|\_\_| |_|_|\__, |_| |_|\__/___\__,_| .__/|_|
#               __/ |                  | |
#              |___/                   |_|
name: KnightzAPI
version: 1.0
main: uk.knightz.knightzapi.KnightzAPI
depend: [Vault]
softdepend: [zdwdqdw]
#Cheeky little Bukkit Explot ;)