name: KnightzAPI
version: 1.0
main: uk.knightz.knightzapi.KnightzAPI
depend: [Vault]
author: Knightz
website: http://bristermitten.me
#Cheeky little Bukkit Exploit to make sure the plugin loads last ;)
softdepend: [Essentials, thisdoesntexist]